controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 1.00
  min_vel_x: 0.50
  max_rotational_vel: 0.75
  min_in_place_rotational_vel: 0.25
  acc_lim_th: 0.785
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: false
  meter_scoring: true
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.4
  goal_distance_bias: 2.0
  path_distance_bias: 8.0
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 10
  vtheta_samples: 20
  dwa: true

