local_pubs: [/tf,/map,/particlecloud,/scan,/move_base_node/TrajectoryPlannerROS/local_plan,/move_base/local_costmap/obstacles,/move_base/local_costmap/inflated_obstacles,/move_base_node/SBPLLatticePlanner/plan] 
foreign_pubs: [] 
