EBandPlannerROS:
  
  #Set the acceleration limits of the robot
  max_acceleration: 1.0
  virtual_mass: 0.75
  max_translational_acceleration: 1.0
  max_rotational_acceleration: 0.785

  #Set the velocity limits of the robot
  max_vel_lin: 1.0
  max_vel_th: 0.5
  min_vel_lin: 0.5
  min_vel_th: 0.0
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0

  rotation_correction_threshold: 0.2
